### ISSUE TITLE
Before-the Hands on lab

### ISSUE THREAD

**Issue by mzbowe** [microsoft/Hybrid-Identity#3]
Task 2 Step #1.  The user may not see **All Services**, as the portal keeps changing.  I defaulted to the new view and you don't see that.  A better method instead of navigating is to type **Subscriptions**in the top Search field......that will always find anything no matter how the portal view is configured.

**Comment by mzbowe** [comment]
Task 2 step 4.  When you go to the IAM Blade, you don't see a list of accounts, Instruct to click the **Role Assignments ** tab.  Then the accounts show.

**Comment by mzbowe** [comment]
Additionally, in Task 4 step 2, if my account does not have those roles, maybe steps or a link "how to"

**Comment by polichtm** [comment]
Hi Mark,
are we assuming that the person running this lab has no knowledge of Azure portal?
rgds
Marcin

**Comment by polichtm** [comment]
Closing since the assumption is that participants have basic knowledge of the Azure portal interface
