### ISSUE TITLE
Task 3 Step 1

### ISSUE THREAD

**Issue by mzbowe** [microsoft/Hybrid-Identity#4]
Seems basic, but I had my window small, so the Chevron for cloud shell did not show at the top.  New folks may not even know it is there.  I even tried search, and it does not come up.  It no longer shows at the bottom, so the newer users need to know how to launch it.  Another option could be to have them go to shell.azure.com on a new tab, which would give them a second window

**Comment by mzbowe** [comment]
Additionally, the instructions don't say to click Bash or PowerShell.  A Linux user will go right for Bash.  Yes, it's obvious when you look at the next steps, but users will fail and fluster.

**Comment by polichtm** [comment]
Hi Mark,
this goes back to my earlier question - are we assuming that the person running this lab has no familiarity with the Azure portal interface? 
If so, maybe this lab is not for them...
rgds
Marcin

**Comment by mzbowe** [comment]
Clear instructions make labs easier and provide less frustration for students. I'm very Azure well versed, but honesty haven't been in the portal for a couple of months, and I have to hunt and peck.  It's not a question of familiarity with the portal interface, its a matter of being very specific in instructions.

**Comment by mzbowe** [comment]
Someone may be very familiar with the portal, but never used the CLoud SHell.  Also, some folks may not be familiar with the portal because they have a develops pipeline, use Visual Studio to push things through, or Ansible etc...

**Comment by polichtm** [comment]
Hi Mark,
the Azure portal interface changes practically on the daily basis. There is a downside to making instructions "very specific" - since most likely they will become inaccurate in not too distant future, which, in turn will increase course maintenance overhead
rgds
Marcin

**Comment by polichtm** [comment]
Hi Mark
btw. step 1 in task 3 states:
"In the Azure Portal, start a PowerShell session in Cloud Shell. "
Would you mind clarifying what you mean by "Additionally, the instructions don't say to click Bash or PowerShell. "?
rgds
Marcin

**Comment by mzbowe** [comment]
When you start Cloud She’ll for the first time, that option appears. On my machine and the subscription I used I had never used it there so it was like starting it from scratch. Now if a user had used it before and had set the preference to one or another it will be all good if they set Cloud Shell to PSH, but if they set it to bash, then they need to switch it over.

Get Outlook<https://aka.ms/qtex0l> for iOS
Please excuse any typos from my big thumbs on my phone

Thank you
Mark Grimes
Microsoft Consulting Services
Azure/Azure Stack Infrastructure specialist
________________________________

**Comment by mzbowe** [comment]
I would bring this up with the original designers. I do not know if this is true or not.

Get Outlook<https://aka.ms/qtex0l> for iOS
Please excuse any typos from my big thumbs on my phone

Thank you
Mark Grimes
Microsoft Consulting Services
Azure/Azure Stack Infrastructure specialist
________________________________

**Comment by polichtm** [comment]
Closing since the assumption is that participants have basic knowledge of the Azure portal interface
